/*
 * Interface wrapper code.
 *
 * Generated by SIP snapshot-4.10.1-637497440cb5 on Sat Apr 24 19:01:03 2010
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 45 "/home/maemo/python-qt4-4.7/sip/QtGui/qmdiarea.sip"
#include <qmdiarea.h>
#line 39 "sipQtGuiQMdiArea.cpp"

#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 43 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qtabwidget.sip"
#include <qtabwidget.h>
#line 46 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 49 "sipQtGuiQMdiArea.cpp"
#line 466 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 52 "sipQtGuiQMdiArea.cpp"
#line 305 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 55 "sipQtGuiQMdiArea.cpp"
#line 428 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 58 "sipQtGuiQMdiArea.cpp"
#line 318 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 61 "sipQtGuiQMdiArea.cpp"
#line 399 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 64 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 67 "sipQtGuiQMdiArea.cpp"
#line 45 "/home/maemo/python-qt4-4.7/sip/QtGui/qmdisubwindow.sip"
#include <qmdisubwindow.h>
#line 70 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qbrush.sip"
#include <qbrush.h>
#line 73 "sipQtGuiQMdiArea.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 76 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 79 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qsize.sip"
#include <qsize.h>
#line 82 "sipQtGuiQMdiArea.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 85 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 88 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qscrollbar.sip"
#include <qscrollbar.h>
#line 91 "sipQtGuiQMdiArea.cpp"
#line 350 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 94 "sipQtGuiQMdiArea.cpp"
#line 565 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 97 "sipQtGuiQMdiArea.cpp"
#line 619 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 100 "sipQtGuiQMdiArea.cpp"
#line 590 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 103 "sipQtGuiQMdiArea.cpp"
#line 607 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 106 "sipQtGuiQMdiArea.cpp"
#line 490 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 109 "sipQtGuiQMdiArea.cpp"
#line 279 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 112 "sipQtGuiQMdiArea.cpp"
#line 238 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 115 "sipQtGuiQMdiArea.cpp"
#line 45 "/home/maemo/python-qt4-4.7/sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 118 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 121 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 124 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qrect.sip"
#include <qrect.h>
#line 127 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qframe.sip"
#include <qframe.h>
#line 130 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 133 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 136 "sipQtGuiQMdiArea.cpp"
#line 45 "/home/maemo/python-qt4-4.7/sip/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 139 "sipQtGuiQMdiArea.cpp"
#line 39 "/home/maemo/python-qt4-4.7/sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 142 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 145 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 148 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 151 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 154 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qregion.sip"
#include <qregion.h>
#line 157 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 160 "sipQtGuiQMdiArea.cpp"
#line 43 "/home/maemo/python-qt4-4.7/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 163 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 166 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 169 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qfont.sip"
#include <qfont.h>
#line 172 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 175 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 178 "sipQtGuiQMdiArea.cpp"
#line 520 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 539 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 183 "sipQtGuiQMdiArea.cpp"
#line 478 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 186 "sipQtGuiQMdiArea.cpp"
#line 675 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 189 "sipQtGuiQMdiArea.cpp"
#line 301 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 192 "sipQtGuiQMdiArea.cpp"
#line 442 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 195 "sipQtGuiQMdiArea.cpp"
#line 414 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 198 "sipQtGuiQMdiArea.cpp"
#line 379 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 201 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 204 "sipQtGuiQMdiArea.cpp"
#line 68 "/home/maemo/python-qt4-4.7/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 207 "sipQtGuiQMdiArea.cpp"
#line 42 "/home/maemo/python-qt4-4.7/sip/QtGui/qx11info_x11.sip"
#include <qx11info_x11.h>
#line 210 "sipQtGuiQMdiArea.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 213 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qaction.sip"
#include <qaction.h>
#line 216 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 219 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 222 "sipQtGuiQMdiArea.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 225 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 228 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 231 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qicon.sip"
#include <qicon.h>
#line 234 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 237 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 240 "sipQtGuiQMdiArea.cpp"
#line 38 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 243 "sipQtGuiQMdiArea.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 246 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 249 "sipQtGuiQMdiArea.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 252 "sipQtGuiQMdiArea.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 255 "sipQtGuiQMdiArea.cpp"


class sipQMdiArea : public QMdiArea
{
public:
    sipQMdiArea(QWidget *);
    virtual ~sipQMdiArea();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    QSize sizeHint() const;
    QSize minimumSizeHint() const;
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void paintEvent(QPaintEvent *);
    void childEvent(QChildEvent *);
    void resizeEvent(QResizeEvent *);
    void timerEvent(QTimerEvent *);
    void showEvent(QShowEvent *);
    bool viewportEvent(QEvent *);
    void scrollContentsBy(int,int);
    void mousePressEvent(QMouseEvent *);
    void mouseReleaseEvent(QMouseEvent *);
    void mouseDoubleClickEvent(QMouseEvent *);
    void mouseMoveEvent(QMouseEvent *);
    void wheelEvent(QWheelEvent *);
    void contextMenuEvent(QContextMenuEvent *);
    void dragEnterEvent(QDragEnterEvent *);
    void dragMoveEvent(QDragMoveEvent *);
    void dragLeaveEvent(QDragLeaveEvent *);
    void dropEvent(QDropEvent *);
    void keyPressEvent(QKeyEvent *);
    void changeEvent(QEvent *);
    int devType() const;
    void setVisible(bool);
    int heightForWidth(int) const;
    QPaintEngine * paintEngine() const;
    void keyReleaseEvent(QKeyEvent *);
    void focusInEvent(QFocusEvent *);
    void focusOutEvent(QFocusEvent *);
    void enterEvent(QEvent *);
    void leaveEvent(QEvent *);
    void moveEvent(QMoveEvent *);
    void closeEvent(QCloseEvent *);
    void tabletEvent(QTabletEvent *);
    void actionEvent(QActionEvent *);
    void hideEvent(QHideEvent *);
    int metric(QPaintDevice::PaintDeviceMetric) const;
    void inputMethodEvent(QInputMethodEvent *);
    QVariant inputMethodQuery(Qt::InputMethodQuery) const;
    bool focusNextPrevChild(bool);
    void enabledChange(bool);
    void paletteChange(const QPalette&);
    void fontChange(const QFont&);
    void windowActivationChange(bool);
    void languageChange();
    void customEvent(QEvent *);
    void connectNotify(const char *);
    void disconnectNotify(const char *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQMdiArea(const sipQMdiArea &);
    sipQMdiArea &operator = (const sipQMdiArea &);

    char sipPyMethods[49];
};

sipQMdiArea::sipQMdiArea(QWidget *a0): QMdiArea(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQMdiArea::~sipQMdiArea()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQMdiArea::metaObject() const
{
    return sip_QtGui_qt_metaobject(sipPySelf,sipType_QMdiArea);
}

int sipQMdiArea::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QMdiArea::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtGui_qt_metacall(sipPySelf,sipType_QMdiArea,_c,_id,_a);

    return _id;
}

void *sipQMdiArea::qt_metacast(const char *_clname)
{
    return (sip_QtGui_qt_metacast && sip_QtGui_qt_metacast(sipPySelf,sipType_QMdiArea,_clname)) ? this : QMdiArea::qt_metacast(_clname);
}

QSize sipQMdiArea::sizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_sizeHint);

    if (!meth)
        return QMdiArea::sizeHint();

    extern QSize sipVH_QtGui_4(sip_gilstate_t,PyObject *);

    return sipVH_QtGui_4(sipGILState,meth);
}

QSize sipQMdiArea::minimumSizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,NULL,sipName_minimumSizeHint);

    if (!meth)
        return QMdiArea::minimumSizeHint();

    extern QSize sipVH_QtGui_4(sip_gilstate_t,PyObject *);

    return sipVH_QtGui_4(sipGILState,meth);
}

bool sipQMdiArea::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_event);

    if (!meth)
        return QMdiArea::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtGui_QtCore->em_virthandlers[5]))(sipGILState,meth,a0);
}

bool sipQMdiArea::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_eventFilter);

    if (!meth)
        return QMdiArea::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_QtGui_QtCore->em_virthandlers[18]))(sipGILState,meth,a0,a1);
}

void sipQMdiArea::paintEvent(QPaintEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_paintEvent);

    if (!meth)
    {
        QMdiArea::paintEvent(a0);
        return;
    }

    extern void sipVH_QtGui_3(sip_gilstate_t,PyObject *,QPaintEvent *);

    sipVH_QtGui_3(sipGILState,meth,a0);
}

void sipQMdiArea::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_childEvent);

    if (!meth)
    {
        QMdiArea::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t,PyObject *,QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_QtGui_QtCore->em_virthandlers[25]))(sipGILState,meth,a0);
}

void sipQMdiArea::resizeEvent(QResizeEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_resizeEvent);

    if (!meth)
    {
        QMdiArea::resizeEvent(a0);
        return;
    }

    extern void sipVH_QtGui_2(sip_gilstate_t,PyObject *,QResizeEvent *);

    sipVH_QtGui_2(sipGILState,meth,a0);
}

void sipQMdiArea::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_timerEvent);

    if (!meth)
    {
        QMdiArea::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t,PyObject *,QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_QtGui_QtCore->em_virthandlers[9]))(sipGILState,meth,a0);
}

void sipQMdiArea::showEvent(QShowEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_showEvent);

    if (!meth)
    {
        QMdiArea::showEvent(a0);
        return;
    }

    extern void sipVH_QtGui_1(sip_gilstate_t,PyObject *,QShowEvent *);

    sipVH_QtGui_1(sipGILState,meth,a0);
}

bool sipQMdiArea::viewportEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_viewportEvent);

    if (!meth)
        return QMdiArea::viewportEvent(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtGui_QtCore->em_virthandlers[5]))(sipGILState,meth,a0);
}

void sipQMdiArea::scrollContentsBy(int a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_scrollContentsBy);

    if (!meth)
    {
        QMdiArea::scrollContentsBy(a0,a1);
        return;
    }

    extern void sipVH_QtGui_32(sip_gilstate_t,PyObject *,int,int);

    sipVH_QtGui_32(sipGILState,meth,a0,a1);
}

void sipQMdiArea::mousePressEvent(QMouseEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_mousePressEvent);

    if (!meth)
    {
        QAbstractScrollArea::mousePressEvent(a0);
        return;
    }

    extern void sipVH_QtGui_26(sip_gilstate_t,PyObject *,QMouseEvent *);

    sipVH_QtGui_26(sipGILState,meth,a0);
}

void sipQMdiArea::mouseReleaseEvent(QMouseEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_mouseReleaseEvent);

    if (!meth)
    {
        QAbstractScrollArea::mouseReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtGui_26(sip_gilstate_t,PyObject *,QMouseEvent *);

    sipVH_QtGui_26(sipGILState,meth,a0);
}

void sipQMdiArea::mouseDoubleClickEvent(QMouseEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_mouseDoubleClickEvent);

    if (!meth)
    {
        QAbstractScrollArea::mouseDoubleClickEvent(a0);
        return;
    }

    extern void sipVH_QtGui_26(sip_gilstate_t,PyObject *,QMouseEvent *);

    sipVH_QtGui_26(sipGILState,meth,a0);
}

void sipQMdiArea::mouseMoveEvent(QMouseEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_mouseMoveEvent);

    if (!meth)
    {
        QAbstractScrollArea::mouseMoveEvent(a0);
        return;
    }

    extern void sipVH_QtGui_26(sip_gilstate_t,PyObject *,QMouseEvent *);

    sipVH_QtGui_26(sipGILState,meth,a0);
}

void sipQMdiArea::wheelEvent(QWheelEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_wheelEvent);

    if (!meth)
    {
        QAbstractScrollArea::wheelEvent(a0);
        return;
    }

    extern void sipVH_QtGui_5(sip_gilstate_t,PyObject *,QWheelEvent *);

    sipVH_QtGui_5(sipGILState,meth,a0);
}

void sipQMdiArea::contextMenuEvent(QContextMenuEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_contextMenuEvent);

    if (!meth)
    {
        QAbstractScrollArea::contextMenuEvent(a0);
        return;
    }

    extern void sipVH_QtGui_21(sip_gilstate_t,PyObject *,QContextMenuEvent *);

    sipVH_QtGui_21(sipGILState,meth,a0);
}

void sipQMdiArea::dragEnterEvent(QDragEnterEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_dragEnterEvent);

    if (!meth)
    {
        QAbstractScrollArea::dragEnterEvent(a0);
        return;
    }

    extern void sipVH_QtGui_18(sip_gilstate_t,PyObject *,QDragEnterEvent *);

    sipVH_QtGui_18(sipGILState,meth,a0);
}

void sipQMdiArea::dragMoveEvent(QDragMoveEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_dragMoveEvent);

    if (!meth)
    {
        QAbstractScrollArea::dragMoveEvent(a0);
        return;
    }

    extern void sipVH_QtGui_17(sip_gilstate_t,PyObject *,QDragMoveEvent *);

    sipVH_QtGui_17(sipGILState,meth,a0);
}

void sipQMdiArea::dragLeaveEvent(QDragLeaveEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_dragLeaveEvent);

    if (!meth)
    {
        QAbstractScrollArea::dragLeaveEvent(a0);
        return;
    }

    extern void sipVH_QtGui_16(sip_gilstate_t,PyObject *,QDragLeaveEvent *);

    sipVH_QtGui_16(sipGILState,meth,a0);
}

void sipQMdiArea::dropEvent(QDropEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_dropEvent);

    if (!meth)
    {
        QAbstractScrollArea::dropEvent(a0);
        return;
    }

    extern void sipVH_QtGui_15(sip_gilstate_t,PyObject *,QDropEvent *);

    sipVH_QtGui_15(sipGILState,meth,a0);
}

void sipQMdiArea::keyPressEvent(QKeyEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_keyPressEvent);

    if (!meth)
    {
        QAbstractScrollArea::keyPressEvent(a0);
        return;
    }

    extern void sipVH_QtGui_25(sip_gilstate_t,PyObject *,QKeyEvent *);

    sipVH_QtGui_25(sipGILState,meth,a0);
}

void sipQMdiArea::changeEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_changeEvent);

    if (!meth)
    {
        QFrame::changeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_QtGui_QtCore->em_virthandlers[17]))(sipGILState,meth,a0);
}

int sipQMdiArea::devType() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[23]),sipPySelf,NULL,sipName_devType);

    if (!meth)
        return QWidget::devType();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_QtGui_QtCore->em_virthandlers[6]))(sipGILState,meth);
}

void sipQMdiArea::setVisible(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_setVisible);

    if (!meth)
    {
        QWidget::setVisible(a0);
        return;
    }

    extern void sipVH_QtGui_6(sip_gilstate_t,PyObject *,bool);

    sipVH_QtGui_6(sipGILState,meth,a0);
}

int sipQMdiArea::heightForWidth(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[25]),sipPySelf,NULL,sipName_heightForWidth);

    if (!meth)
        return QWidget::heightForWidth(a0);

    extern int sipVH_QtGui_28(sip_gilstate_t,PyObject *,int);

    return sipVH_QtGui_28(sipGILState,meth,a0);
}

QPaintEngine * sipQMdiArea::paintEngine() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[26]),sipPySelf,NULL,sipName_paintEngine);

    if (!meth)
        return QWidget::paintEngine();

    extern QPaintEngine * sipVH_QtGui_27(sip_gilstate_t,PyObject *);

    return sipVH_QtGui_27(sipGILState,meth);
}

void sipQMdiArea::keyReleaseEvent(QKeyEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_keyReleaseEvent);

    if (!meth)
    {
        QWidget::keyReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtGui_25(sip_gilstate_t,PyObject *,QKeyEvent *);

    sipVH_QtGui_25(sipGILState,meth,a0);
}

void sipQMdiArea::focusInEvent(QFocusEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_focusInEvent);

    if (!meth)
    {
        QWidget::focusInEvent(a0);
        return;
    }

    extern void sipVH_QtGui_24(sip_gilstate_t,PyObject *,QFocusEvent *);

    sipVH_QtGui_24(sipGILState,meth,a0);
}

void sipQMdiArea::focusOutEvent(QFocusEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_focusOutEvent);

    if (!meth)
    {
        QWidget::focusOutEvent(a0);
        return;
    }

    extern void sipVH_QtGui_24(sip_gilstate_t,PyObject *,QFocusEvent *);

    sipVH_QtGui_24(sipGILState,meth,a0);
}

void sipQMdiArea::enterEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_enterEvent);

    if (!meth)
    {
        QWidget::enterEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_QtGui_QtCore->em_virthandlers[17]))(sipGILState,meth,a0);
}

void sipQMdiArea::leaveEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_leaveEvent);

    if (!meth)
    {
        QWidget::leaveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_QtGui_QtCore->em_virthandlers[17]))(sipGILState,meth,a0);
}

void sipQMdiArea::moveEvent(QMoveEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[32],sipPySelf,NULL,sipName_moveEvent);

    if (!meth)
    {
        QWidget::moveEvent(a0);
        return;
    }

    extern void sipVH_QtGui_23(sip_gilstate_t,PyObject *,QMoveEvent *);

    sipVH_QtGui_23(sipGILState,meth,a0);
}

void sipQMdiArea::closeEvent(QCloseEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[33],sipPySelf,NULL,sipName_closeEvent);

    if (!meth)
    {
        QWidget::closeEvent(a0);
        return;
    }

    extern void sipVH_QtGui_22(sip_gilstate_t,PyObject *,QCloseEvent *);

    sipVH_QtGui_22(sipGILState,meth,a0);
}

void sipQMdiArea::tabletEvent(QTabletEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[34],sipPySelf,NULL,sipName_tabletEvent);

    if (!meth)
    {
        QWidget::tabletEvent(a0);
        return;
    }

    extern void sipVH_QtGui_20(sip_gilstate_t,PyObject *,QTabletEvent *);

    sipVH_QtGui_20(sipGILState,meth,a0);
}

void sipQMdiArea::actionEvent(QActionEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[35],sipPySelf,NULL,sipName_actionEvent);

    if (!meth)
    {
        QWidget::actionEvent(a0);
        return;
    }

    extern void sipVH_QtGui_19(sip_gilstate_t,PyObject *,QActionEvent *);

    sipVH_QtGui_19(sipGILState,meth,a0);
}

void sipQMdiArea::hideEvent(QHideEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[36],sipPySelf,NULL,sipName_hideEvent);

    if (!meth)
    {
        QWidget::hideEvent(a0);
        return;
    }

    extern void sipVH_QtGui_0(sip_gilstate_t,PyObject *,QHideEvent *);

    sipVH_QtGui_0(sipGILState,meth,a0);
}

int sipQMdiArea::metric(QPaintDevice::PaintDeviceMetric a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[37]),sipPySelf,NULL,sipName_metric);

    if (!meth)
        return QWidget::metric(a0);

    extern int sipVH_QtGui_14(sip_gilstate_t,PyObject *,QPaintDevice::PaintDeviceMetric);

    return sipVH_QtGui_14(sipGILState,meth,a0);
}

void sipQMdiArea::inputMethodEvent(QInputMethodEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[38],sipPySelf,NULL,sipName_inputMethodEvent);

    if (!meth)
    {
        QWidget::inputMethodEvent(a0);
        return;
    }

    extern void sipVH_QtGui_13(sip_gilstate_t,PyObject *,QInputMethodEvent *);

    sipVH_QtGui_13(sipGILState,meth,a0);
}

QVariant sipQMdiArea::inputMethodQuery(Qt::InputMethodQuery a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[39]),sipPySelf,NULL,sipName_inputMethodQuery);

    if (!meth)
        return QWidget::inputMethodQuery(a0);

    extern QVariant sipVH_QtGui_12(sip_gilstate_t,PyObject *,Qt::InputMethodQuery);

    return sipVH_QtGui_12(sipGILState,meth,a0);
}

bool sipQMdiArea::focusNextPrevChild(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[40],sipPySelf,NULL,sipName_focusNextPrevChild);

    if (!meth)
        return QWidget::focusNextPrevChild(a0);

    extern bool sipVH_QtGui_11(sip_gilstate_t,PyObject *,bool);

    return sipVH_QtGui_11(sipGILState,meth,a0);
}

void sipQMdiArea::enabledChange(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[41],sipPySelf,NULL,sipName_enabledChange);

    if (!meth)
    {
        QWidget::enabledChange(a0);
        return;
    }

    extern void sipVH_QtGui_6(sip_gilstate_t,PyObject *,bool);

    sipVH_QtGui_6(sipGILState,meth,a0);
}

void sipQMdiArea::paletteChange(const QPalette& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[42],sipPySelf,NULL,sipName_paletteChange);

    if (!meth)
    {
        QWidget::paletteChange(a0);
        return;
    }

    extern void sipVH_QtGui_10(sip_gilstate_t,PyObject *,const QPalette&);

    sipVH_QtGui_10(sipGILState,meth,a0);
}

void sipQMdiArea::fontChange(const QFont& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[43],sipPySelf,NULL,sipName_fontChange);

    if (!meth)
    {
        QWidget::fontChange(a0);
        return;
    }

    extern void sipVH_QtGui_9(sip_gilstate_t,PyObject *,const QFont&);

    sipVH_QtGui_9(sipGILState,meth,a0);
}

void sipQMdiArea::windowActivationChange(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[44],sipPySelf,NULL,sipName_windowActivationChange);

    if (!meth)
    {
        QWidget::windowActivationChange(a0);
        return;
    }

    extern void sipVH_QtGui_6(sip_gilstate_t,PyObject *,bool);

    sipVH_QtGui_6(sipGILState,meth,a0);
}

void sipQMdiArea::languageChange()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[45],sipPySelf,NULL,sipName_languageChange);

    if (!meth)
    {
        QWidget::languageChange();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t,PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_QtGui_QtCore->em_virthandlers[11]))(sipGILState,meth);
}

void sipQMdiArea::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[46],sipPySelf,NULL,sipName_customEvent);

    if (!meth)
    {
        QObject::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_QtGui_QtCore->em_virthandlers[17]))(sipGILState,meth,a0);
}

void sipQMdiArea::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[47],sipPySelf,NULL,sipName_connectNotify);

    if (!meth)
    {
        QObject::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_QtGui_QtCore->em_virthandlers[24]))(sipGILState,meth,a0);
}

void sipQMdiArea::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[48],sipPySelf,NULL,sipName_disconnectNotify);

    if (!meth)
    {
        QObject::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_QtGui_QtCore->em_virthandlers[24]))(sipGILState,meth,a0);
}


PyDoc_STRVAR(doc_QMdiArea_sizeHint, "QMdiArea.sizeHint() -> QSize");

extern "C" {static PyObject *meth_QMdiArea_sizeHint(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_sizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QSize *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QSize((sipSelfWasArg ? sipCpp->QMdiArea::sizeHint() : sipCpp->sizeHint()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_sizeHint, doc_QMdiArea_sizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_minimumSizeHint, "QMdiArea.minimumSizeHint() -> QSize");

extern "C" {static PyObject *meth_QMdiArea_minimumSizeHint(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_minimumSizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QSize *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QSize((sipSelfWasArg ? sipCpp->QMdiArea::minimumSizeHint() : sipCpp->minimumSizeHint()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_minimumSizeHint, doc_QMdiArea_minimumSizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_activeSubWindow, "QMdiArea.activeSubWindow() -> QMdiSubWindow");

extern "C" {static PyObject *meth_QMdiArea_activeSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_activeSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QMdiSubWindow *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->activeSubWindow();
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_QMdiSubWindow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_activeSubWindow, doc_QMdiArea_activeSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_addSubWindow, "QMdiArea.addSubWindow(QWidget, Qt.WindowFlags flags=0) -> QMdiSubWindow");

extern "C" {static PyObject *meth_QMdiArea_addSubWindow(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_addSubWindow(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        Qt::WindowFlags a1def = 0;
        Qt::WindowFlags * a1 = &a1def;
        int a1State = 0;
        QMdiArea *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_flags,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ:|J1", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QWidget, &a0, sipType_Qt_WindowFlags, &a1, &a1State))
        {
            QMdiSubWindow *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->addSubWindow(a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(a1,sipType_Qt_WindowFlags,a1State);

            return sipConvertFromType(sipRes,sipType_QMdiSubWindow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_addSubWindow, doc_QMdiArea_addSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_subWindowList, "QMdiArea.subWindowList(QMdiArea.WindowOrder order=QMdiArea.CreationOrder) -> list-of-QMdiSubWindow");

extern "C" {static PyObject *meth_QMdiArea_subWindowList(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_subWindowList(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea::WindowOrder a0 = QMdiArea::CreationOrder;
        QMdiArea *sipCpp;

        static const char *sipKwdList[] = {
            sipName_order,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "B|E", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiArea_WindowOrder, &a0))
        {
            QList<QMdiSubWindow *> *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QList<QMdiSubWindow *>(sipCpp->subWindowList(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QList_0101QMdiSubWindow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_subWindowList, doc_QMdiArea_subWindowList);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_currentSubWindow, "QMdiArea.currentSubWindow() -> QMdiSubWindow");

extern "C" {static PyObject *meth_QMdiArea_currentSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_currentSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QMdiSubWindow *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->currentSubWindow();
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_QMdiSubWindow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_currentSubWindow, doc_QMdiArea_currentSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_removeSubWindow, "QMdiArea.removeSubWindow(QWidget)");

extern "C" {static PyObject *meth_QMdiArea_removeSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_removeSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        PyObject *a0Wrapper;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B@J8", &sipSelf, sipType_QMdiArea, &sipCpp, &a0Wrapper, sipType_QWidget, &a0))
        {
#line 84 "/home/maemo/python-qt4-4.7/sip/QtGui/qmdiarea.sip"
        // We need to implement /TransferBack/ on the argument, but it might be the
        // QMdiSubWindow that wraps the widget we are really after.
        QMdiSubWindow *swin = qobject_cast<QMdiSubWindow *>(a0);
        
        if (swin)
        {
            QWidget *w = swin->widget();
        
            a0Wrapper = (w ? sipGetPyObject(w, sipType_QWidget) : 0);
        }
        else
            a0Wrapper = 0;
        
        Py_BEGIN_ALLOW_THREADS
        sipCpp->removeSubWindow(a0);
        Py_END_ALLOW_THREADS
        
        if (a0Wrapper)
            sipTransferBack(a0Wrapper);
#line 1445 "sipQtGuiQMdiArea.cpp"

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_removeSubWindow, doc_QMdiArea_removeSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_background, "QMdiArea.background() -> QBrush");

extern "C" {static PyObject *meth_QMdiArea_background(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_background(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QBrush *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QBrush(sipCpp->background());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QBrush,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_background, doc_QMdiArea_background);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setBackground, "QMdiArea.setBackground(QBrush)");

extern "C" {static PyObject *meth_QMdiArea_setBackground(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setBackground(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QBrush * a0;
        int a0State = 0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QBrush, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setBackground(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QBrush *>(a0),sipType_QBrush,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setBackground, doc_QMdiArea_setBackground);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setOption, "QMdiArea.setOption(QMdiArea.AreaOption, bool on=True)");

extern "C" {static PyObject *meth_QMdiArea_setOption(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setOption(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea::AreaOption a0;
        bool a1 = 1;
        QMdiArea *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_on,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BE|b", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiArea_AreaOption, &a0, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setOption(a0,a1);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setOption, doc_QMdiArea_setOption);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_testOption, "QMdiArea.testOption(QMdiArea.AreaOption) -> bool");

extern "C" {static PyObject *meth_QMdiArea_testOption(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_testOption(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea::AreaOption a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiArea_AreaOption, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->testOption(a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_testOption, doc_QMdiArea_testOption);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setActiveSubWindow, "QMdiArea.setActiveSubWindow(QMdiSubWindow)");

extern "C" {static PyObject *meth_QMdiArea_setActiveSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setActiveSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiSubWindow * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiSubWindow, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setActiveSubWindow(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setActiveSubWindow, doc_QMdiArea_setActiveSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_tileSubWindows, "QMdiArea.tileSubWindows()");

extern "C" {static PyObject *meth_QMdiArea_tileSubWindows(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_tileSubWindows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->tileSubWindows();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_tileSubWindows, doc_QMdiArea_tileSubWindows);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_cascadeSubWindows, "QMdiArea.cascadeSubWindows()");

extern "C" {static PyObject *meth_QMdiArea_cascadeSubWindows(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_cascadeSubWindows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->cascadeSubWindows();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_cascadeSubWindows, doc_QMdiArea_cascadeSubWindows);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_closeActiveSubWindow, "QMdiArea.closeActiveSubWindow()");

extern "C" {static PyObject *meth_QMdiArea_closeActiveSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_closeActiveSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->closeActiveSubWindow();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_closeActiveSubWindow, doc_QMdiArea_closeActiveSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_closeAllSubWindows, "QMdiArea.closeAllSubWindows()");

extern "C" {static PyObject *meth_QMdiArea_closeAllSubWindows(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_closeAllSubWindows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->closeAllSubWindows();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_closeAllSubWindows, doc_QMdiArea_closeAllSubWindows);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_activateNextSubWindow, "QMdiArea.activateNextSubWindow()");

extern "C" {static PyObject *meth_QMdiArea_activateNextSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_activateNextSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->activateNextSubWindow();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_activateNextSubWindow, doc_QMdiArea_activateNextSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_activatePreviousSubWindow, "QMdiArea.activatePreviousSubWindow()");

extern "C" {static PyObject *meth_QMdiArea_activatePreviousSubWindow(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_activatePreviousSubWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->activatePreviousSubWindow();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_activatePreviousSubWindow, doc_QMdiArea_activatePreviousSubWindow);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setupViewport, "QMdiArea.setupViewport(QWidget)");

extern "C" {static PyObject *meth_QMdiArea_setupViewport(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setupViewport(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QWidget, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setupViewport(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setupViewport, doc_QMdiArea_setupViewport);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_event, "QMdiArea.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QMdiArea_event(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QMdiArea::event(a0) : sipCpp->event(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_event, doc_QMdiArea_event);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_eventFilter, "QMdiArea.eventFilter(QObject, QEvent) -> bool");

extern "C" {static PyObject *meth_QMdiArea_eventFilter(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_eventFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QObject * a0;
        QEvent * a1;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8J8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QObject, &a0, sipType_QEvent, &a1))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QMdiArea::eventFilter(a0,a1) : sipCpp->eventFilter(a0,a1));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_eventFilter, doc_QMdiArea_eventFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_paintEvent, "QMdiArea.paintEvent(QPaintEvent)");

extern "C" {static PyObject *meth_QMdiArea_paintEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_paintEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QPaintEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QPaintEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::paintEvent(a0) : sipCpp->paintEvent(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_paintEvent, doc_QMdiArea_paintEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_childEvent, "QMdiArea.childEvent(QChildEvent)");

extern "C" {static PyObject *meth_QMdiArea_childEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_childEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QChildEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QChildEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::childEvent(a0) : sipCpp->childEvent(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_childEvent, doc_QMdiArea_childEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_resizeEvent, "QMdiArea.resizeEvent(QResizeEvent)");

extern "C" {static PyObject *meth_QMdiArea_resizeEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_resizeEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QResizeEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QResizeEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::resizeEvent(a0) : sipCpp->resizeEvent(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_resizeEvent, doc_QMdiArea_resizeEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_timerEvent, "QMdiArea.timerEvent(QTimerEvent)");

extern "C" {static PyObject *meth_QMdiArea_timerEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_timerEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QTimerEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::timerEvent(a0) : sipCpp->timerEvent(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_timerEvent, doc_QMdiArea_timerEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_showEvent, "QMdiArea.showEvent(QShowEvent)");

extern "C" {static PyObject *meth_QMdiArea_showEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_showEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QShowEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QShowEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::showEvent(a0) : sipCpp->showEvent(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_showEvent, doc_QMdiArea_showEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_viewportEvent, "QMdiArea.viewportEvent(QEvent) -> bool");

extern "C" {static PyObject *meth_QMdiArea_viewportEvent(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_viewportEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent * a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QMdiArea::viewportEvent(a0) : sipCpp->viewportEvent(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_viewportEvent, doc_QMdiArea_viewportEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_scrollContentsBy, "QMdiArea.scrollContentsBy(int, int)");

extern "C" {static PyObject *meth_QMdiArea_scrollContentsBy(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_scrollContentsBy(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        int a1;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pii", &sipSelf, sipType_QMdiArea, &sipCpp, &a0, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QMdiArea::scrollContentsBy(a0,a1) : sipCpp->scrollContentsBy(a0,a1));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_scrollContentsBy, doc_QMdiArea_scrollContentsBy);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_activationOrder, "QMdiArea.activationOrder() -> QMdiArea.WindowOrder");

extern "C" {static PyObject *meth_QMdiArea_activationOrder(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_activationOrder(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QMdiArea::WindowOrder sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->activationOrder();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QMdiArea_WindowOrder);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_activationOrder, doc_QMdiArea_activationOrder);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setActivationOrder, "QMdiArea.setActivationOrder(QMdiArea.WindowOrder)");

extern "C" {static PyObject *meth_QMdiArea_setActivationOrder(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setActivationOrder(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea::WindowOrder a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiArea_WindowOrder, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setActivationOrder(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setActivationOrder, doc_QMdiArea_setActivationOrder);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setViewMode, "QMdiArea.setViewMode(QMdiArea.ViewMode)");

extern "C" {static PyObject *meth_QMdiArea_setViewMode(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setViewMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea::ViewMode a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QMdiArea_ViewMode, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setViewMode(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setViewMode, doc_QMdiArea_setViewMode);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_viewMode, "QMdiArea.viewMode() -> QMdiArea.ViewMode");

extern "C" {static PyObject *meth_QMdiArea_viewMode(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_viewMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QMdiArea::ViewMode sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->viewMode();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QMdiArea_ViewMode);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_viewMode, doc_QMdiArea_viewMode);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setTabShape, "QMdiArea.setTabShape(QTabWidget.TabShape)");

extern "C" {static PyObject *meth_QMdiArea_setTabShape(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setTabShape(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTabWidget::TabShape a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QTabWidget_TabShape, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setTabShape(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setTabShape, doc_QMdiArea_setTabShape);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_tabShape, "QMdiArea.tabShape() -> QTabWidget.TabShape");

extern "C" {static PyObject *meth_QMdiArea_tabShape(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_tabShape(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QTabWidget::TabShape sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->tabShape();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QTabWidget_TabShape);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_tabShape, doc_QMdiArea_tabShape);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setTabPosition, "QMdiArea.setTabPosition(QTabWidget.TabPosition)");

extern "C" {static PyObject *meth_QMdiArea_setTabPosition(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setTabPosition(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTabWidget::TabPosition a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QMdiArea, &sipCpp, sipType_QTabWidget_TabPosition, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setTabPosition(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setTabPosition, doc_QMdiArea_setTabPosition);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_tabPosition, "QMdiArea.tabPosition() -> QTabWidget.TabPosition");

extern "C" {static PyObject *meth_QMdiArea_tabPosition(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_tabPosition(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            QTabWidget::TabPosition sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->tabPosition();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QTabWidget_TabPosition);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_tabPosition, doc_QMdiArea_tabPosition);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_documentMode, "QMdiArea.documentMode() -> bool");

extern "C" {static PyObject *meth_QMdiArea_documentMode(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_documentMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMdiArea, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->documentMode();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_documentMode, doc_QMdiArea_documentMode);

    return NULL;
}


PyDoc_STRVAR(doc_QMdiArea_setDocumentMode, "QMdiArea.setDocumentMode(bool)");

extern "C" {static PyObject *meth_QMdiArea_setDocumentMode(PyObject *, PyObject *);}
static PyObject *meth_QMdiArea_setDocumentMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QMdiArea *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QMdiArea, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setDocumentMode(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMdiArea, sipName_setDocumentMode, doc_QMdiArea_setDocumentMode);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QMdiArea(void *, const sipTypeDef *);}
static void *cast_QMdiArea(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QMdiArea)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QAbstractScrollArea)->ctd_cast((QAbstractScrollArea *)(QMdiArea *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QMdiArea(void *, int);}
static void release_QMdiArea(void *sipCppV,int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQMdiArea *>(sipCppV);
    else
        delete reinterpret_cast<QMdiArea *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QMdiArea(sipSimpleWrapper *);}
static void dealloc_QMdiArea(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQMdiArea *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QMdiArea(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QMdiArea(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QMdiArea(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQMdiArea *sipCpp = 0;

    {
        QWidget * a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QWidget, &a0, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQMdiArea(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QMdiArea[] = {{21, 255, 1}};


static PyMethodDef methods_QMdiArea[] = {
    {SIP_MLNAME_CAST(sipName_activateNextSubWindow), meth_QMdiArea_activateNextSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_activateNextSubWindow)},
    {SIP_MLNAME_CAST(sipName_activatePreviousSubWindow), meth_QMdiArea_activatePreviousSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_activatePreviousSubWindow)},
    {SIP_MLNAME_CAST(sipName_activationOrder), meth_QMdiArea_activationOrder, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_activationOrder)},
    {SIP_MLNAME_CAST(sipName_activeSubWindow), meth_QMdiArea_activeSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_activeSubWindow)},
    {SIP_MLNAME_CAST(sipName_addSubWindow), (PyCFunction)meth_QMdiArea_addSubWindow, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QMdiArea_addSubWindow)},
    {SIP_MLNAME_CAST(sipName_background), meth_QMdiArea_background, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_background)},
    {SIP_MLNAME_CAST(sipName_cascadeSubWindows), meth_QMdiArea_cascadeSubWindows, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_cascadeSubWindows)},
    {SIP_MLNAME_CAST(sipName_childEvent), meth_QMdiArea_childEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_childEvent)},
    {SIP_MLNAME_CAST(sipName_closeActiveSubWindow), meth_QMdiArea_closeActiveSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_closeActiveSubWindow)},
    {SIP_MLNAME_CAST(sipName_closeAllSubWindows), meth_QMdiArea_closeAllSubWindows, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_closeAllSubWindows)},
    {SIP_MLNAME_CAST(sipName_currentSubWindow), meth_QMdiArea_currentSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_currentSubWindow)},
    {SIP_MLNAME_CAST(sipName_documentMode), meth_QMdiArea_documentMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_documentMode)},
    {SIP_MLNAME_CAST(sipName_event), meth_QMdiArea_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_event)},
    {SIP_MLNAME_CAST(sipName_eventFilter), meth_QMdiArea_eventFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_eventFilter)},
    {SIP_MLNAME_CAST(sipName_minimumSizeHint), meth_QMdiArea_minimumSizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_minimumSizeHint)},
    {SIP_MLNAME_CAST(sipName_paintEvent), meth_QMdiArea_paintEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_paintEvent)},
    {SIP_MLNAME_CAST(sipName_removeSubWindow), meth_QMdiArea_removeSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_removeSubWindow)},
    {SIP_MLNAME_CAST(sipName_resizeEvent), meth_QMdiArea_resizeEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_resizeEvent)},
    {SIP_MLNAME_CAST(sipName_scrollContentsBy), meth_QMdiArea_scrollContentsBy, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_scrollContentsBy)},
    {SIP_MLNAME_CAST(sipName_setActivationOrder), meth_QMdiArea_setActivationOrder, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setActivationOrder)},
    {SIP_MLNAME_CAST(sipName_setActiveSubWindow), meth_QMdiArea_setActiveSubWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setActiveSubWindow)},
    {SIP_MLNAME_CAST(sipName_setBackground), meth_QMdiArea_setBackground, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setBackground)},
    {SIP_MLNAME_CAST(sipName_setDocumentMode), meth_QMdiArea_setDocumentMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setDocumentMode)},
    {SIP_MLNAME_CAST(sipName_setOption), (PyCFunction)meth_QMdiArea_setOption, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QMdiArea_setOption)},
    {SIP_MLNAME_CAST(sipName_setTabPosition), meth_QMdiArea_setTabPosition, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setTabPosition)},
    {SIP_MLNAME_CAST(sipName_setTabShape), meth_QMdiArea_setTabShape, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setTabShape)},
    {SIP_MLNAME_CAST(sipName_setViewMode), meth_QMdiArea_setViewMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setViewMode)},
    {SIP_MLNAME_CAST(sipName_setupViewport), meth_QMdiArea_setupViewport, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_setupViewport)},
    {SIP_MLNAME_CAST(sipName_showEvent), meth_QMdiArea_showEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_showEvent)},
    {SIP_MLNAME_CAST(sipName_sizeHint), meth_QMdiArea_sizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_sizeHint)},
    {SIP_MLNAME_CAST(sipName_subWindowList), (PyCFunction)meth_QMdiArea_subWindowList, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QMdiArea_subWindowList)},
    {SIP_MLNAME_CAST(sipName_tabPosition), meth_QMdiArea_tabPosition, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_tabPosition)},
    {SIP_MLNAME_CAST(sipName_tabShape), meth_QMdiArea_tabShape, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_tabShape)},
    {SIP_MLNAME_CAST(sipName_testOption), meth_QMdiArea_testOption, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_testOption)},
    {SIP_MLNAME_CAST(sipName_tileSubWindows), meth_QMdiArea_tileSubWindows, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_tileSubWindows)},
    {SIP_MLNAME_CAST(sipName_timerEvent), meth_QMdiArea_timerEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_timerEvent)},
    {SIP_MLNAME_CAST(sipName_viewMode), meth_QMdiArea_viewMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_viewMode)},
    {SIP_MLNAME_CAST(sipName_viewportEvent), meth_QMdiArea_viewportEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QMdiArea_viewportEvent)}
};

static sipEnumMemberDef enummembers_QMdiArea[] = {
    {sipName_ActivationHistoryOrder, QMdiArea::ActivationHistoryOrder, 336},
    {sipName_CreationOrder, QMdiArea::CreationOrder, 336},
    {sipName_DontMaximizeSubWindowOnActivation, QMdiArea::DontMaximizeSubWindowOnActivation, 333},
    {sipName_StackingOrder, QMdiArea::StackingOrder, 336},
    {sipName_SubWindowView, QMdiArea::SubWindowView, 335},
    {sipName_TabbedView, QMdiArea::TabbedView, 335},
};


/* Define this type's PyQt4 signals. */
static const pyqt4QtSignal pyqt4_signals_QMdiArea[] = {
    {"subWindowActivated(QMdiSubWindow *)", "\1QMdiArea.subWindowActivated(QMdiSubWindow)", 0},
    {0, 0, 0}
};

PyDoc_STRVAR(doc_QMdiArea, "\1QMdiArea(QWidget parent=None)");


pyqt4ClassTypeDef sipTypeDef_QtGui_QMdiArea = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QMdiArea,
        {0}
    },
    {
        sipNameNr_QMdiArea,
        {0, 0, 1},
        38, methods_QMdiArea,
        6, enummembers_QMdiArea,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QMdiArea,
    -1,
    -1,
    supers_QMdiArea,
    0,
    init_QMdiArea,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QMdiArea,
    0,
    0,
    0,
    release_QMdiArea,
    cast_QMdiArea,
    0,
    0,
    0
},
    &QMdiArea::staticMetaObject,
    0,
    pyqt4_signals_QMdiArea
};
