/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10-snapshot-20100108 on Tue Feb 16 16:32:13 2010
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtDesigner.h"

#line 37 "/home/maemo/python-qt4-4.7/sip/QtDesigner/abstractwidgetbox.sip"
#include <abstractwidgetbox.h>
#line 39 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"

#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 43 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 46 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 49 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 39 "/home/maemo/python-qt4-4.7/sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 52 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 55 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 58 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 61 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qregion.sip"
#include <qregion.h>
#line 64 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 67 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 70 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 43 "/home/maemo/python-qt4-4.7/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 73 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 76 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qsize.sip"
#include <qsize.h>
#line 79 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qrect.sip"
#include <qrect.h>
#line 82 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 85 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 88 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qfont.sip"
#include <qfont.h>
#line 91 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 94 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 97 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 520 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 539 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 102 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 105 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 478 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 108 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 466 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 111 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 565 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 114 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 619 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 117 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 590 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 120 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 607 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 123 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 675 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 126 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 301 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 129 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 490 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 132 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 442 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 135 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 428 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 138 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 414 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 141 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 399 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 144 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 379 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 147 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 350 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 150 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 279 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 153 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 238 "/home/maemo/python-qt4-4.7/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 159 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 68 "/home/maemo/python-qt4-4.7/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 162 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 42 "/home/maemo/python-qt4-4.7/sip/QtGui/qx11info_x11.sip"
#include <qx11info_x11.h>
#line 165 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 168 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qaction.sip"
#include <qaction.h>
#line 171 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 174 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 177 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 180 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 183 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 186 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qicon.sip"
#include <qicon.h>
#line 189 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 192 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 195 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 318 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 198 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 305 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 201 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 204 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 38 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 207 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 210 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 213 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 216 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 219 "sipQtDesignerQDesignerWidgetBoxInterface.cpp"


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_setFileName, "QDesignerWidgetBoxInterface.setFileName(QString)");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const QString * a0;
        int a0State = 0;
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp, sipType_QString,&a0, &a0State))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_setFileName);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipCpp->setFileName(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_setFileName, doc_QDesignerWidgetBoxInterface_setFileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_fileName, "QDesignerWidgetBoxInterface.fileName() -> QString");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            QString *sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_fileName);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->fileName());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_fileName, doc_QDesignerWidgetBoxInterface_fileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_load, "QDesignerWidgetBoxInterface.load() -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_load);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->load();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_load, doc_QDesignerWidgetBoxInterface_load);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_save, "QDesignerWidgetBoxInterface.save() -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_save);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->save();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_save, doc_QDesignerWidgetBoxInterface_save);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QDesignerWidgetBoxInterface(void *, const sipTypeDef *);}
static void *cast_QDesignerWidgetBoxInterface(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QDesignerWidgetBoxInterface)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QWidget)->ctd_cast((QWidget *)(QDesignerWidgetBoxInterface *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDesignerWidgetBoxInterface(void *, int);}
static void release_QDesignerWidgetBoxInterface(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QDesignerWidgetBoxInterface *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *);}
static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QDesignerWidgetBoxInterface(sipSelf->u.cppPtr,0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDesignerWidgetBoxInterface[] = {{679, 1, 1}};


static PyMethodDef methods_QDesignerWidgetBoxInterface[] = {
    {SIP_MLNAME_CAST(sipName_fileName), meth_QDesignerWidgetBoxInterface_fileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_fileName)},
    {SIP_MLNAME_CAST(sipName_load), meth_QDesignerWidgetBoxInterface_load, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_load)},
    {SIP_MLNAME_CAST(sipName_save), meth_QDesignerWidgetBoxInterface_save, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_save)},
    {SIP_MLNAME_CAST(sipName_setFileName), meth_QDesignerWidgetBoxInterface_setFileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_setFileName)}
};


pyqt4ClassTypeDef sipTypeDef_QtDesigner_QDesignerWidgetBoxInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QDesignerWidgetBoxInterface,
        {0}
    },
    {
        sipNameNr_QDesignerWidgetBoxInterface,
        {0, 0, 1},
        4, methods_QDesignerWidgetBoxInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    release_QDesignerWidgetBoxInterface,
    cast_QDesignerWidgetBoxInterface,
    0,
    0,
    0
},
    &QDesignerWidgetBoxInterface::staticMetaObject,
    0,
    0
};
