/*
 * Interface wrapper code.
 *
 * Generated by SIP snapshot-4.10.1-637497440cb5 on Sat Apr 24 19:00:59 2010
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 104 "/home/maemo/python-qt4-4.7/sip/QtCore/qreadwritelock.sip"
#include <qreadwritelock.h>
#line 39 "sipQtCoreQWriteLocker.cpp"

#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qreadwritelock.sip"
#include <qreadwritelock.h>
#line 43 "sipQtCoreQWriteLocker.cpp"


PyDoc_STRVAR(doc_QWriteLocker_unlock, "QWriteLocker.unlock()");

extern "C" {static PyObject *meth_QWriteLocker_unlock(PyObject *, PyObject *);}
static PyObject *meth_QWriteLocker_unlock(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWriteLocker *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWriteLocker, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->unlock();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWriteLocker, sipName_unlock, doc_QWriteLocker_unlock);

    return NULL;
}


PyDoc_STRVAR(doc_QWriteLocker_relock, "QWriteLocker.relock()");

extern "C" {static PyObject *meth_QWriteLocker_relock(PyObject *, PyObject *);}
static PyObject *meth_QWriteLocker_relock(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWriteLocker *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWriteLocker, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->relock();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWriteLocker, sipName_relock, doc_QWriteLocker_relock);

    return NULL;
}


PyDoc_STRVAR(doc_QWriteLocker_readWriteLock, "QWriteLocker.readWriteLock() -> QReadWriteLock");

extern "C" {static PyObject *meth_QWriteLocker_readWriteLock(PyObject *, PyObject *);}
static PyObject *meth_QWriteLocker_readWriteLock(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWriteLocker *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWriteLocker, &sipCpp))
        {
            QReadWriteLock *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->readWriteLock();
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_QReadWriteLock,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWriteLocker, sipName_readWriteLock, doc_QWriteLocker_readWriteLock);

    return NULL;
}


PyDoc_STRVAR(doc_QWriteLocker___enter__, "QWriteLocker.__enter__() -> object");

extern "C" {static PyObject *meth_QWriteLocker___enter__(PyObject *, PyObject *);}
static PyObject *meth_QWriteLocker___enter__(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWriteLocker *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWriteLocker, &sipCpp))
        {
            PyObject * sipRes = 0;

#line 115 "/home/maemo/python-qt4-4.7/sip/QtCore/qreadwritelock.sip"
        // Just return a reference to self.
        sipRes = sipSelf;
        Py_INCREF(sipRes);
#line 153 "sipQtCoreQWriteLocker.cpp"

            return sipRes;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWriteLocker, sipName___enter__, doc_QWriteLocker___enter__);

    return NULL;
}


PyDoc_STRVAR(doc_QWriteLocker___exit__, "QWriteLocker.__exit__(object, object, object)");

extern "C" {static PyObject *meth_QWriteLocker___exit__(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QWriteLocker___exit__(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        PyObject * a0;
        PyObject * a1;
        PyObject * a2;
        QWriteLocker *sipCpp;

        static const char *sipKwdList[] = {
            sipName_type,
            sipName_value,
            sipName_traceback,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BP0P0P0", &sipSelf, sipType_QWriteLocker, &sipCpp, &a0, &a1, &a2))
        {
#line 122 "/home/maemo/python-qt4-4.7/sip/QtCore/qreadwritelock.sip"
        sipCpp->unlock();
#line 190 "sipQtCoreQWriteLocker.cpp"

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWriteLocker, sipName___exit__, doc_QWriteLocker___exit__);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QWriteLocker(void *, const sipTypeDef *);}
static void *cast_QWriteLocker(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QWriteLocker)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QWriteLocker(void *, int);}
static void release_QWriteLocker(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QWriteLocker *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QWriteLocker(sipSimpleWrapper *);}
static void dealloc_QWriteLocker(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QWriteLocker(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QWriteLocker(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QWriteLocker(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QWriteLocker *sipCpp = 0;

    {
        QReadWriteLock * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8", sipType_QReadWriteLock, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QWriteLocker(a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_QWriteLocker[] = {
    {SIP_MLNAME_CAST(sipName___enter__), meth_QWriteLocker___enter__, METH_VARARGS, SIP_MLDOC_CAST(doc_QWriteLocker___enter__)},
    {SIP_MLNAME_CAST(sipName___exit__), (PyCFunction)meth_QWriteLocker___exit__, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QWriteLocker___exit__)},
    {SIP_MLNAME_CAST(sipName_readWriteLock), meth_QWriteLocker_readWriteLock, METH_VARARGS, SIP_MLDOC_CAST(doc_QWriteLocker_readWriteLock)},
    {SIP_MLNAME_CAST(sipName_relock), meth_QWriteLocker_relock, METH_VARARGS, SIP_MLDOC_CAST(doc_QWriteLocker_relock)},
    {SIP_MLNAME_CAST(sipName_unlock), meth_QWriteLocker_unlock, METH_VARARGS, SIP_MLDOC_CAST(doc_QWriteLocker_unlock)}
};

PyDoc_STRVAR(doc_QWriteLocker, "\1QWriteLocker(QReadWriteLock)");


pyqt4ClassTypeDef sipTypeDef_QtCore_QWriteLocker = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QWriteLocker,
        {0}
    },
    {
        sipNameNr_QWriteLocker,
        {0, 0, 1},
        5, methods_QWriteLocker,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QWriteLocker,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    0,
    init_QWriteLocker,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QWriteLocker,
    0,
    0,
    0,
    release_QWriteLocker,
    cast_QWriteLocker,
    0,
    0,
    0
},
    0,
    0,
    0
};
