/*
 * Interface wrapper code.
 *
 * Generated by SIP snapshot-4.10.1-637497440cb5 on Sat Apr 24 19:01:07 2010
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtMaemo5.h"

#line 45 "/home/maemo/python-qt4-4.7/sip/QtMaemo5/qmaemo5abstractpickselector.sip"
#include <qmaemo5abstractpickselector.h>
#line 39 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"

#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 43 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 46 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 49 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 52 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 318 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 55 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 305 "/home/maemo/python-qt4-4.7/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 58 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 61 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 38 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 64 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 43 "/home/maemo/python-qt4-4.7/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 67 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 40 "/home/maemo/python-qt4-4.7/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 70 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 125 "/home/maemo/python-qt4-4.7/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 73 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 76 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 41 "/home/maemo/python-qt4-4.7/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 79 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"
#line 37 "/home/maemo/python-qt4-4.7/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 82 "sipQtMaemo5QMaemo5AbstractPickSelector.cpp"


class sipQMaemo5AbstractPickSelector : public QMaemo5AbstractPickSelector
{
public:
    sipQMaemo5AbstractPickSelector(QObject *);
    virtual ~sipQMaemo5AbstractPickSelector();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    QWidget * widget(QWidget *);
    QString currentValueText() const;
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QEvent *);
    void connectNotify(const char *);
    void disconnectNotify(const char *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQMaemo5AbstractPickSelector(const sipQMaemo5AbstractPickSelector &);
    sipQMaemo5AbstractPickSelector &operator = (const sipQMaemo5AbstractPickSelector &);

    char sipPyMethods[9];
};

sipQMaemo5AbstractPickSelector::sipQMaemo5AbstractPickSelector(QObject *a0): QMaemo5AbstractPickSelector(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQMaemo5AbstractPickSelector::~sipQMaemo5AbstractPickSelector()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQMaemo5AbstractPickSelector::metaObject() const
{
    return sip_QtMaemo5_qt_metaobject(sipPySelf,sipType_QMaemo5AbstractPickSelector);
}

int sipQMaemo5AbstractPickSelector::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QMaemo5AbstractPickSelector::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtMaemo5_qt_metacall(sipPySelf,sipType_QMaemo5AbstractPickSelector,_c,_id,_a);

    return _id;
}

void *sipQMaemo5AbstractPickSelector::qt_metacast(const char *_clname)
{
    return (sip_QtMaemo5_qt_metacast && sip_QtMaemo5_qt_metacast(sipPySelf,sipType_QMaemo5AbstractPickSelector,_clname)) ? this : QMaemo5AbstractPickSelector::qt_metacast(_clname);
}

QWidget * sipQMaemo5AbstractPickSelector::widget(QWidget *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,sipName_QMaemo5AbstractPickSelector,sipName_widget);

    if (!meth)
        return 0;

    extern QWidget * sipVH_QtMaemo5_0(sip_gilstate_t,PyObject *,QWidget *);

    return sipVH_QtMaemo5_0(sipGILState,meth,a0);
}

QString sipQMaemo5AbstractPickSelector::currentValueText() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,sipName_QMaemo5AbstractPickSelector,sipName_currentValueText);

    if (!meth)
        return QString();

    typedef QString (*sipVH_QtCore_62)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_62)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[62]))(sipGILState,meth);
}

bool sipQMaemo5AbstractPickSelector::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_event);

    if (!meth)
        return QObject::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[5]))(sipGILState,meth,a0);
}

bool sipQMaemo5AbstractPickSelector::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_eventFilter);

    if (!meth)
        return QObject::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[18]))(sipGILState,meth,a0,a1);
}

void sipQMaemo5AbstractPickSelector::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!meth)
    {
        QObject::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t,PyObject *,QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[9]))(sipGILState,meth,a0);
}

void sipQMaemo5AbstractPickSelector::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_childEvent);

    if (!meth)
    {
        QObject::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t,PyObject *,QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[25]))(sipGILState,meth,a0);
}

void sipQMaemo5AbstractPickSelector::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_customEvent);

    if (!meth)
    {
        QObject::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[17]))(sipGILState,meth,a0);
}

void sipQMaemo5AbstractPickSelector::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_connectNotify);

    if (!meth)
    {
        QObject::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[24]))(sipGILState,meth,a0);
}

void sipQMaemo5AbstractPickSelector::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_disconnectNotify);

    if (!meth)
    {
        QObject::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_QtMaemo5_QtCore->em_virthandlers[24]))(sipGILState,meth,a0);
}


PyDoc_STRVAR(doc_QMaemo5AbstractPickSelector_widget, "QMaemo5AbstractPickSelector.widget(QWidget) -> QWidget");

extern "C" {static PyObject *meth_QMaemo5AbstractPickSelector_widget(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QMaemo5AbstractPickSelector_widget(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QWidget * a0;
        QMaemo5AbstractPickSelector *sipCpp;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ8", &sipSelf, sipType_QMaemo5AbstractPickSelector, &sipCpp, sipType_QWidget, &a0))
        {
            QWidget *sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QMaemo5AbstractPickSelector, sipName_widget);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->widget(a0);
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_QWidget,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMaemo5AbstractPickSelector, sipName_widget, doc_QMaemo5AbstractPickSelector_widget);

    return NULL;
}


PyDoc_STRVAR(doc_QMaemo5AbstractPickSelector_currentValueText, "QMaemo5AbstractPickSelector.currentValueText() -> QString");

extern "C" {static PyObject *meth_QMaemo5AbstractPickSelector_currentValueText(PyObject *, PyObject *);}
static PyObject *meth_QMaemo5AbstractPickSelector_currentValueText(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        QMaemo5AbstractPickSelector *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMaemo5AbstractPickSelector, &sipCpp))
        {
            QString *sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QMaemo5AbstractPickSelector, sipName_currentValueText);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->currentValueText());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMaemo5AbstractPickSelector, sipName_currentValueText, doc_QMaemo5AbstractPickSelector_currentValueText);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QMaemo5AbstractPickSelector(void *, const sipTypeDef *);}
static void *cast_QMaemo5AbstractPickSelector(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QMaemo5AbstractPickSelector)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QObject)->ctd_cast((QObject *)(QMaemo5AbstractPickSelector *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QMaemo5AbstractPickSelector(void *, int);}
static void release_QMaemo5AbstractPickSelector(void *sipCppV,int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQMaemo5AbstractPickSelector *>(sipCppV);
    else
        delete reinterpret_cast<QMaemo5AbstractPickSelector *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QMaemo5AbstractPickSelector(sipSimpleWrapper *);}
static void dealloc_QMaemo5AbstractPickSelector(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQMaemo5AbstractPickSelector *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QMaemo5AbstractPickSelector(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QMaemo5AbstractPickSelector(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QMaemo5AbstractPickSelector(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipQMaemo5AbstractPickSelector *sipCpp = 0;

    {
        QObject * a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|J8", sipType_QObject, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQMaemo5AbstractPickSelector(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QMaemo5AbstractPickSelector[] = {{129, 0, 1}};


static PyMethodDef methods_QMaemo5AbstractPickSelector[] = {
    {SIP_MLNAME_CAST(sipName_currentValueText), meth_QMaemo5AbstractPickSelector_currentValueText, METH_VARARGS, SIP_MLDOC_CAST(doc_QMaemo5AbstractPickSelector_currentValueText)},
    {SIP_MLNAME_CAST(sipName_widget), (PyCFunction)meth_QMaemo5AbstractPickSelector_widget, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QMaemo5AbstractPickSelector_widget)}
};


/* Define this type's PyQt4 signals. */
static const pyqt4QtSignal pyqt4_signals_QMaemo5AbstractPickSelector[] = {
    {"selected(const QString&)", "\1QMaemo5AbstractPickSelector.selected(QString)", 0},
    {0, 0, 0}
};

PyDoc_STRVAR(doc_QMaemo5AbstractPickSelector, "\1QMaemo5AbstractPickSelector(QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_QtMaemo5_QMaemo5AbstractPickSelector = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QMaemo5AbstractPickSelector,
        {0}
    },
    {
        sipNameNr_QMaemo5AbstractPickSelector,
        {0, 0, 1},
        2, methods_QMaemo5AbstractPickSelector,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QMaemo5AbstractPickSelector,
    -1,
    -1,
    supers_QMaemo5AbstractPickSelector,
    0,
    init_QMaemo5AbstractPickSelector,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QMaemo5AbstractPickSelector,
    0,
    0,
    0,
    release_QMaemo5AbstractPickSelector,
    cast_QMaemo5AbstractPickSelector,
    0,
    0,
    0
},
    &QMaemo5AbstractPickSelector::staticMetaObject,
    0,
    pyqt4_signals_QMaemo5AbstractPickSelector
};
